import * as pitch from './pitch';

describe('pitch.isOpenString() tests', () => {
    const errortable: [ string, string, number ][] = [
        [ 'pitch is not a number', 'violin', '60' as unknown as number ],
        [ 'instrument is invalid', 'bass viol', 66 ],
    ];

    test.each(errortable)('throws when %s', (_, inst, n) => {
        expect(() => pitch.isOpenString(inst, n)).toThrow();
    });

    const table: [ string, number, boolean ][] = [
        [ 'violin', 28, false ],
        [ 'violin', 33, false ],
        [ 'violin', 36, false ],
        [ 'violin', 38, false ],
        [ 'violin', 43, false ],
        [ 'violin', 48, false ],
        [ 'violin', 50, false ],
        [ 'violin', 55, true ],
        [ 'violin', 57, false ],
        [ 'violin', 62, true ],
        [ 'violin', 69, true ],
        [ 'violin', 76, true ],
        [ 'viola', 28, false ],
        [ 'viola', 33, false ],
        [ 'viola', 36, false ],
        [ 'viola', 38, false ],
        [ 'viola', 43, false ],
        [ 'viola', 48, true ],
        [ 'viola', 55, true ],
        [ 'viola', 57, false ],
        [ 'viola', 62, true ],
        [ 'viola', 69, true ],
        [ 'viola', 76, false ],
        [ 'cello', 28, false ],
        [ 'cello', 33, false ],
        [ 'cello', 38, false ],
        [ 'cello', 36, true ],
        [ 'cello', 43, true ],
        [ 'cello', 48, false ],
        [ 'cello', 50, true ],
        [ 'cello', 55, false ],
        [ 'cello', 57, true ],
        [ 'cello', 62, false ],
        [ 'cello', 69, false ],
        [ 'viola', 76, false ],
        [ 'double bass', 28, true ],
        [ 'double bass', 33, true ],
        [ 'double bass', 36, false ],
        [ 'double bass', 38, true ],
        [ 'double bass', 43, true ],
        [ 'double bass', 48, false ],
        [ 'double bass', 50, false ],
        [ 'double bass', 55, false ],
        [ 'double bass', 57, false ],
        [ 'double bass', 62, false ],
        [ 'double bass', 69, false ],
        [ 'double bass', 76, false ],
    ];

    test.each(table)('instrument: %p, pitch: %p', (inst, n, ret) => {
        expect(pitch.isOpenString(inst, n)).toBe(ret);
    });
});

describe('pitch.isNaturalHarmonic() tests', () => {
    const errortable: [ string, string, number ][] = [
        [ 'pitch is not a number', 'violin', '60' as unknown as number ],
        [ 'instrument is invalid', 'bass viol', 66 ],
    ];

    test.each(errortable)('throws when %s', (_, inst, n) => {
        expect(() => pitch.isNaturalHarmonic(inst, n)).toThrow();
    });

    const table: [ string, number, boolean ][] = [
        [ 'violin', 47, false ],
        [ 'violin', 52, false ],
        [ 'violin', 55, false ],
        [ 'violin', 56, false ],
        [ 'violin', 57, false ],
        [ 'violin', 60, false ],
        [ 'violin', 61, false ],
        [ 'violin', 62, false ],
        [ 'violin', 64, false ],
        [ 'violin', 66, false ],
        [ 'violin', 67, false ],
        [ 'violin', 69, false ],
        [ 'violin', 70, false ],
        [ 'violin', 71, false ],
        [ 'violin', 72, false ],
        [ 'violin', 74, true ],
        [ 'violin', 76, false ],
        [ 'violin', 78, false ],
        [ 'violin', 79, true ],
        [ 'violin', 81, true ],
        [ 'violin', 83, true ],
        [ 'violin', 85, false ],
        [ 'violin', 86, true ],
        [ 'violin', 88, true ],
        [ 'violin', 90, true ],
        [ 'violin', 93, true ],
        [ 'violin', 95, true ],
        [ 'violin', 97, true ],
        [ 'violin', 100, true ],
        [ 'violin', 104, true ],
        [ 'viola', 47, false ],
        [ 'viola', 52, false ],
        [ 'viola', 55, false ],
        [ 'viola', 56, false ],
        [ 'viola', 57, false ],
        [ 'viola', 60, false ],
        [ 'viola', 61, false ],
        [ 'viola', 62, false ],
        [ 'viola', 64, false ],
        [ 'viola', 66, false ],
        [ 'viola', 67, true ],
        [ 'viola', 69, false ],
        [ 'viola', 70, false ],
        [ 'viola', 71, false ],
        [ 'viola', 72, true ],
        [ 'viola', 74, true ],
        [ 'viola', 76, true ],
        [ 'viola', 78, false ],
        [ 'viola', 79, true ],
        [ 'viola', 81, true ],
        [ 'viola', 83, true ],
        [ 'viola', 85, false ],
        [ 'viola', 86, true ],
        [ 'viola', 88, true ],
        [ 'viola', 90, true ],
        [ 'viola', 93, true ],
        [ 'viola', 95, false ],
        [ 'viola', 97, true ],
        [ 'viola', 100, false ],
        [ 'viola', 104, false ],
        [ 'cello', 47, false ],
        [ 'cello', 52, false ],
        [ 'cello', 55, true ],
        [ 'cello', 56, false ],
        [ 'cello', 57, false ],
        [ 'cello', 60, true ],
        [ 'cello', 61, false ],
        [ 'cello', 62, true ],
        [ 'cello', 64, true ],
        [ 'cello', 66, false ],
        [ 'cello', 67, true ],
        [ 'cello', 69, true ],
        [ 'cello', 70, false ],
        [ 'cello', 71, true ],
        [ 'cello', 72, false ],
        [ 'cello', 74, true ],
        [ 'cello', 76, true ],
        [ 'cello', 78, true ],
        [ 'cello', 79, false ],
        [ 'cello', 81, true ],
        [ 'cello', 83, false ],
        [ 'cello', 85, true ],
        [ 'cello', 86, false ],
        [ 'cello', 88, false ],
        [ 'cello', 90, false ],
        [ 'cello', 93, false ],
        [ 'cello', 95, false ],
        [ 'cello', 97, false ],
        [ 'cello', 100, false ],
        [ 'cello', 104, false ],
        [ 'double bass', 47, true ],
        [ 'double bass', 52, true ],
        [ 'double bass', 55, false ],
        [ 'double bass', 56, true ],
        [ 'double bass', 57, true ],
        [ 'double bass', 60, false ],
        [ 'double bass', 61, true ],
        [ 'double bass', 62, true ],
        [ 'double bass', 64, false ],
        [ 'double bass', 66, true ],
        [ 'double bass', 67, true ],
        [ 'double bass', 69, false ],
        [ 'double bass', 70, false ],
        [ 'double bass', 71, true ],
        [ 'double bass', 72, false ],
        [ 'double bass', 74, false ],
        [ 'double bass', 76, false ],
        [ 'double bass', 78, false ],
        [ 'double bass', 79, false ],
        [ 'double bass', 81, false ],
        [ 'double bass', 83, false ],
        [ 'double bass', 85, false ],
        [ 'double bass', 86, false ],
        [ 'double bass', 88, false ],
        [ 'double bass', 90, false ],
        [ 'double bass', 93, false ],
        [ 'double bass', 95, false ],
        [ 'double bass', 97, false ],
        [ 'double bass', 100, false ],
        [ 'double bass', 104, false ],
    ];

    test.each(table)('instrument: %p, pitch: %p', (inst, n, ret) => {
        expect(pitch.isNaturalHarmonic(inst, n)).toBe(ret);
    });
});